
#include "common.hpp"
#include "cdb_file.hpp"

void CDBFile::readStringTable()
{
  if (fileBufSize < 24 ||
      readUInt64() != 0x0000000848544542ULL)            // "BETH", 8
  {
    errorMessage("invalid CDB file header");
  }
  if (readUInt32() != 4U)
    errorMessage("unsupported CDB file version");
  if (readUInt32() < 2U || readUInt32() != 0x54525453U) // "STRT"
    errorMessage("missing string table in CDB file");
  // create string table
  unsigned int  n = readUInt32();
  if ((filePos + std::uint64_t(n)) > fileBufSize)
    errorMessage("unexpected end of CDB file");
  stringMap.resize(n, std::int16_t(-1));
  for ( ; n; n--)
  {
    unsigned int  strtOffs = (unsigned int) (filePos - 24);
    const char  *s = reinterpret_cast< const char * >(fileBuf + filePos);
    for ( ; readUInt8Fast(); n--)
    {
      if (!n)
        errorMessage("string table is not terminated in CDB file");
      stringMap[strtOffs] = std::int16_t(findString(s));
      if (stringMap[strtOffs] < 0)
      {
        std::fprintf(stderr,
                     "Warning: unrecognized string in CDB file: '%s'\n", s);
      }
    }
  }
}

int CDBFile::findString(const char *s)
{
  size_t  n0 = 19;
  size_t  n2 = sizeof(stringTable) / sizeof(char *);
  while (n2 > (n0 + 1))
  {
    size_t  n1 = (n0 + n2) >> 1;
    if (std::strcmp(s, stringTable[n1]) < 0)
      n2 = n1;
    else
      n0 = n1;
  }
  if (n2 > n0 && std::strcmp(s, stringTable[n0]) == 0)
    return int(n0);
  return -1;
}

size_t CDBFile::findString(unsigned int strtOffs) const
{
  if (strtOffs < stringMap.size())
  {
    int     n = stringMap[strtOffs];
    if (n >= 0)
      return size_t(n);
  }
  unsigned int  n = strtOffs - 0xFFFFFF01U;
  return size_t(std::min(n, 18U));
}

const char * CDBFile::stringTable[1141] =
{
  "None",                                               //    0
  "String",                                             //    1
  "List",                                               //    2
  "Map",                                                //    3
  "Ref",                                                //    4
  "Unknown_-250",                                       //    5
  "Unknown_-249",                                       //    6
  "Int8",                                               //    7
  "UInt8",                                              //    8
  "Int16",                                              //    9
  "UInt16",                                             //   10
  "Int32",                                              //   11
  "UInt32",                                             //   12
  "Int64",                                              //   13
  "UInt64",                                             //   14
  "Bool",                                               //   15
  "Float",                                              //   16
  "Double",                                             //   17
  "Unknown",                                            //   18
  "AOVertexColorChannel",                               //   19
  "Absolute",                                           //   20
  "ActiveLayersMask",                                   //   21
  "ActorValueBindings",                                 //   22
  "ActorValueSnapshot",                                 //   23
  "ActorValueSnapshot::ActorValueBinding",              //   24
  "AdaptSpeedDown",                                     //   25
  "AdaptSpeedUp",                                       //   26
  "AdaptiveEmittance",                                  //   27
  "Address",                                            //   28
  "AerosolAbsorbtion",                                  //   29
  "AerosolDensity",                                     //   30
  "AerosolPhaseFunction",                               //   31
  "Albedo",                                             //   32
  "AlbedoPaletteTex",                                   //   33
  "AlbedoTint",                                         //   34
  "AlbedoTintColor",                                    //   35
  "AllowReapply",                                       //   36
  "Alpha",                                              //   37
  "AlphaAdd",                                           //   38
  "AlphaBias",                                          //   39
  "AlphaChannel",                                       //   40
  "AlphaDistance",                                      //   41
  "AlphaMultiply",                                      //   42
  "AlphaPaletteTex",                                    //   43
  "AlphaTestThreshold",                                 //   44
  "AlphaTint",                                          //   45
  "AmbientOcclusion",                                   //   46
  "Anchor",                                             //   47
  "AnimatedDecalIgnoresTAA",                            //   48
  "Anisotropy",                                         //   49
  "Aperture",                                           //   50
  "ApplyExternalEmittanceToAllMaterials",               //   51
  "ApplyFlowOnANMR",                                    //   52
  "ApplyFlowOnEmissivity",                              //   53
  "ApplyFlowOnOpacity",                                 //   54
  "ApplyNodeRotation",                                  //   55
  "ApplyToAllChildren",                                 //   56
  "AssetDataA",                                         //   57
  "AssetName",                                          //   58
  "AtmosphereType",                                     //   59
  "AttachSoundToRefr",                                  //   60
  "AttachType",                                         //   61
  "Attachment",                                         //   62
  "AutoExposure",                                       //   63
  "AutoPlay",                                           //   64
  "BGSAtmosphere",                                      //   65
  "BGSAtmosphere::AtmosphereSettings",                  //   66
  "BGSAtmosphere::CelestialBodySettings",               //   67
  "BGSAtmosphere::MiscSettings",                        //   68
  "BGSAtmosphere::OverrideSettings",                    //   69
  "BGSAtmosphere::ScatteringSettings",                  //   70
  "BGSAtmosphere::ScatteringSettings::MieSettings",     //   71
  "BGSAtmosphere::ScatteringSettings::RayleighSettings",        //   72
  "BGSAtmosphere::StarSettings",                        //   73
  "BGSAudio::WwiseGUID",                                //   74
  "BGSAudio::WwiseSoundHook",                           //   75
  "BGSCloudForm",                                       //   76
  "BGSCloudForm::CloudLayer",                           //   77
  "BGSCloudForm::CloudPlane",                           //   78
  "BGSCloudForm::ShadowParams",                         //   79
  "BGSCurve3DForm",                                     //   80
  "BGSCurveForm",                                       //   81
  "BGSEffectSequenceForm",                              //   82
  "BGSEffectSequenceFormComponent",                     //   83
  "BGSFogVolumeForm",                                   //   84
  "BGSForceData",                                       //   85
  "BGSFormFolderKeywordList",                           //   86
  "BGSLayeredMaterialSwap",                             //   87
  "BGSLayeredMaterialSwap::Entry",                      //   88
  "BGSLodOwnerComponent",                               //   89
  "BGSMaterialPathForm",                                //   90
  "BGSMaterialPropertyComponent",                       //   91
  "BGSMaterialPropertyComponent::Entry",                //   92
  "BGSParticleSystemDefineCollection",                  //   93
  "BGSSpacePhysicsFormComponent",                       //   94
  "BGSTimeOfDayData",                                   //   95
  "BGSVolumetricLighting",                              //   96
  "BGSVolumetricLightingSettings",                      //   97
  "BGSVolumetricLightingSettings::DistantLightingSettings",     //   98
  "BGSVolumetricLightingSettings::ExteriorAndInteriorSettings", //   99
  "BGSVolumetricLightingSettings::ExteriorSettings",    //  100
  "BGSVolumetricLightingSettings::FogDensitySettings",  //  101
  "BGSVolumetricLightingSettings::FogMapSettings",      //  102
  "BGSVolumetricLightingSettings::FogThicknessSettings",        //  103
  "BGSVolumetricLightingSettings::HorizonFogSettings",  //  104
  "BGSWeatherSettingsForm",                             //  105
  "BGSWeatherSettingsForm::ColorSettings",              //  106
  "BGSWeatherSettingsForm::FoliageSettings",            //  107
  "BGSWeatherSettingsForm::MagicEffect",                //  108
  "BGSWeatherSettingsForm::PrecipitationSettings",      //  109
  "BGSWeatherSettingsForm::SoundEffectSettings",        //  110
  "BGSWeatherSettingsForm::SpellEffect",                //  111
  "BGSWeatherSettingsForm::SpellSettings",              //  112
  "BGSWeatherSettingsForm::WeatherChoiceSettings",      //  113
  "BGSWeatherSettingsForm::WeatherSound",               //  114
  "BSAttachConfig::ArtObjectAttach",                    //  115
  "BSAttachConfig::AttachmentConfiguration",            //  116
  "BSAttachConfig::LensFlareAttachment",                //  117
  "BSAttachConfig::LightAttachment",                    //  118
  "BSAttachConfig::NodeAttachment",                     //  119
  "BSAttachConfig::NodeName",                           //  120
  "BSAttachConfig::ObjectAttachment",                   //  121
  "BSAttachConfig::ParticleAttachment",                 //  122
  "BSAttachConfig::SearchRootNode",                     //  123
  "BSAttachConfig::SearchSingleNameSingleNode",         //  124
  "BSAttachConfig::SoundAttachment",                    //  125
  "BSBind::Address",                                    //  126
  "BSBind::ColorCurveController",                       //  127
  "BSBind::ColorLerpController",                        //  128
  "BSBind::ComponentProperty",                          //  129
  "BSBind::ControllerComponent",                        //  130
  "BSBind::Controllers",                                //  131
  "BSBind::Controllers::Mapping",                       //  132
  "BSBind::Directory",                                  //  133
  "BSBind::DirectoryComponent",                         //  134
  "BSBind::Float2DCurveController",                     //  135
  "BSBind::Float2DLerpController",                      //  136
  "BSBind::Float3DCurveController",                     //  137
  "BSBind::Float3DLerpController",                      //  138
  "BSBind::FloatCurveController",                       //  139
  "BSBind::FloatLerpController",                        //  140
  "BSBind::Multiplex",                                  //  141
  "BSBind::Snapshot",                                   //  142
  "BSBind::Snapshot::Entry",                            //  143
  "BSBind::TimerController",                            //  144
  "BSBlendable::ColorValue",                            //  145
  "BSBlendable::FloatValue",                            //  146
  "BSColorCurve",                                       //  147
  "BSComponentDB2::DBFileIndex",                        //  148
  "BSComponentDB2::DBFileIndex::ComponentInfo",         //  149
  "BSComponentDB2::DBFileIndex::ComponentTypeInfo",     //  150
  "BSComponentDB2::DBFileIndex::EdgeInfo",              //  151
  "BSComponentDB2::DBFileIndex::ObjectInfo",            //  152
  "BSComponentDB2::ID",                                 //  153
  "BSComponentDB::CTName",                              //  154
  "BSFloat2DCurve",                                     //  155
  "BSFloat3DCurve",                                     //  156
  "BSFloatCurve",                                       //  157
  "BSFloatCurve::Control",                              //  158
  "BSGalaxy::BGSSunPresetForm",                         //  159
  "BSGalaxy::BGSSunPresetForm::DawnDuskSettings",       //  160
  "BSGalaxy::BGSSunPresetForm::NightSettings",          //  161
  "BSHoudini::HoudiniAssetData",                        //  162
  "BSHoudini::HoudiniAssetData::Parameter",             //  163
  "BSMaterial::AlphaBlenderSettings",                   //  164
  "BSMaterial::AlphaSettingsComponent",                 //  165
  "BSMaterial::BlendModeComponent",                     //  166
  "BSMaterial::BlendParamFloat",                        //  167
  "BSMaterial::BlenderID",                              //  168
  "BSMaterial::Channel",                                //  169
  "BSMaterial::CollisionComponent",                     //  170
  "BSMaterial::Color",                                  //  171
  "BSMaterial::ColorChannelTypeComponent",              //  172
  "BSMaterial::ColorRemapSettingsComponent",            //  173
  "BSMaterial::DecalSettingsComponent",                 //  174
  "BSMaterial::DetailBlenderSettings",                  //  175
  "BSMaterial::DetailBlenderSettingsComponent",         //  176
  "BSMaterial::DistortionComponent",                    //  177
  "BSMaterial::EffectSettingsComponent",                //  178
  "BSMaterial::EmissiveSettingsComponent",              //  179
  "BSMaterial::EmittanceSettings",                      //  180
  "BSMaterial::EyeSettingsComponent",                   //  181
  "BSMaterial::FlipbookComponent",                      //  182
  "BSMaterial::FlowSettingsComponent",                  //  183
  "BSMaterial::GlobalLayerDataComponent",               //  184
  "BSMaterial::GlobalLayerNoiseSettings",               //  185
  "BSMaterial::HairSettingsComponent",                  //  186
  "BSMaterial::Internal::CompiledDB",                   //  187
  "BSMaterial::Internal::CompiledDB::FilePair",         //  188
  "BSMaterial::LODMaterialID",                          //  189
  "BSMaterial::LayerID",                                //  190
  "BSMaterial::LayeredEdgeFalloffComponent",            //  191
  "BSMaterial::LayeredEmissivityComponent",             //  192
  "BSMaterial::LevelOfDetailSettings",                  //  193
  "BSMaterial::MRTextureFile",                          //  194
  "BSMaterial::MaterialID",                             //  195
  "BSMaterial::MaterialOverrideColorTypeComponent",     //  196
  "BSMaterial::MaterialParamFloat",                     //  197
  "BSMaterial::MouthSettingsComponent",                 //  198
  "BSMaterial::Offset",                                 //  199
  "BSMaterial::OpacityComponent",                       //  200
  "BSMaterial::ParamBool",                              //  201
  "BSMaterial::PhysicsMaterialType",                    //  202
  "BSMaterial::ProjectedDecalSettings",                 //  203
  "BSMaterial::Scale",                                  //  204
  "BSMaterial::ShaderModelComponent",                   //  205
  "BSMaterial::ShaderRouteComponent",                   //  206
  "BSMaterial::SourceTextureWithReplacement",           //  207
  "BSMaterial::StarmapBodyEffectComponent",             //  208
  "BSMaterial::TerrainSettingsComponent",               //  209
  "BSMaterial::TerrainTintSettingsComponent",           //  210
  "BSMaterial::TextureAddressModeComponent",            //  211
  "BSMaterial::TextureFile",                            //  212
  "BSMaterial::TextureReplacement",                     //  213
  "BSMaterial::TextureResolutionSetting",               //  214
  "BSMaterial::TextureSetID",                           //  215
  "BSMaterial::TextureSetKindComponent",                //  216
  "BSMaterial::TranslucencySettings",                   //  217
  "BSMaterial::TranslucencySettingsComponent",          //  218
  "BSMaterial::UVStreamID",                             //  219
  "BSMaterial::UVStreamParamBool",                      //  220
  "BSMaterial::VegetationSettingsComponent",            //  221
  "BSMaterial::WaterFoamSettingsComponent",             //  222
  "BSMaterial::WaterGrimeSettingsComponent",            //  223
  "BSMaterial::WaterSettingsComponent",                 //  224
  "BSMaterialBinding::MaterialPropertyNode",            //  225
  "BSMaterialBinding::MaterialUVStreamPropertyNode",    //  226
  "BSResource::ID",                                     //  227
  "BSSequence::AnimationEvent",                         //  228
  "BSSequence::AnimationTrack",                         //  229
  "BSSequence::CameraShakeEvent",                       //  230
  "BSSequence::CameraShakeStrengthTrack",               //  231
  "BSSequence::CameraShakeTrack",                       //  232
  "BSSequence::ColorCurveEvent",                        //  233
  "BSSequence::ColorLerpEvent",                         //  234
  "BSSequence::ColorTriggerEvent",                      //  235
  "BSSequence::CullEvent",                              //  236
  "BSSequence::DissolveEvent",                          //  237
  "BSSequence::DissolveFrequencyScaleTrack",            //  238
  "BSSequence::DissolveOffsetTrack",                    //  239
  "BSSequence::DissolveTrack",                          //  240
  "BSSequence::ExplosionObjectSpawn",                   //  241
  "BSSequence::Float2LerpEvent",                        //  242
  "BSSequence::Float2TriggerEvent",                     //  243
  "BSSequence::FloatCurveEvent",                        //  244
  "BSSequence::FloatLerpEvent",                         //  245
  "BSSequence::FloatNoiseEvent",                        //  246
  "BSSequence::FloatTriggerEvent",                      //  247
  "BSSequence::ImageSpaceLifetimeEvent",                //  248
  "BSSequence::ImageSpaceStrengthTrack",                //  249
  "BSSequence::ImageSpaceTrack",                        //  250
  "BSSequence::ImpactEffectEvent",                      //  251
  "BSSequence::ImpactEffectTrack",                      //  252
  "BSSequence::LightColorTrack",                        //  253
  "BSSequence::LightEffectReferenceTrack",              //  254
  "BSSequence::LightEffectTrack",                       //  255
  "BSSequence::LightIntensityTrack",                    //  256
  "BSSequence::LightLensFlareVisiblityTrack",           //  257
  "BSSequence::LightRadiusTrack",                       //  258
  "BSSequence::LightSpawnEvent",                        //  259
  "BSSequence::LoopMarker",                             //  260
  "BSSequence::MaterialFlipbookIndexGeneratorEvent",    //  261
  "BSSequence::MaterialFlipbookIndexTrack",             //  262
  "BSSequence::MaterialPropertyTrack",                  //  263
  "BSSequence::MaterialTrack",                          //  264
  "BSSequence::NoteEvent",                              //  265
  "BSSequence::NoteTrack",                              //  266
  "BSSequence::ObjectAttachmentTrack",                  //  267
  "BSSequence::ObjectSpawnEvent",                       //  268
  "BSSequence::ObjectSpawnTrack",                       //  269
  "BSSequence::ParticleEffectReferenceTrack",           //  270
  "BSSequence::ParticleEffectTrack",                    //  271
  "BSSequence::ParticleEvent",                          //  272
  "BSSequence::ParticleParameterTrack",                 //  273
  "BSSequence::PlaySubSequenceEvent",                   //  274
  "BSSequence::PositionTrack",                          //  275
  "BSSequence::ProjectedDecalAlphaTrack",               //  276
  "BSSequence::ProjectedDecalSpawnEvent",               //  277
  "BSSequence::ProjectedDecalTrack",                    //  278
  "BSSequence::PropertyControllerEvent",                //  279
  "BSSequence::PropertyLerpControllerEvent",            //  280
  "BSSequence::ReferenceSpawnEvent",                    //  281
  "BSSequence::RevertMaterialOverrideEvent",            //  282
  "BSSequence::RotationTrack",                          //  283
  "BSSequence::ScaleTrack",                             //  284
  "BSSequence::SceneNodeTrack",                         //  285
  "BSSequence::Sequence",                               //  286
  "BSSequence::SetPropertyEvent",                       //  287
  "BSSequence::SoundEvent",                             //  288
  "BSSequence::SoundTrack",                             //  289
  "BSSequence::SubSequenceTrack",                       //  290
  "BSSequence::TrackGroup",                             //  291
  "BSSequence::TriggerMaterialSwap",                    //  292
  "BSSequence::VectorCurveEvent",                       //  293
  "BSSequence::VectorLerpEvent",                        //  294
  "BSSequence::VectorNoiseEvent",                       //  295
  "BSSequence::VectorTriggerEvent",                     //  296
  "BSSequence::VisibilityTrack",                        //  297
  "BSTRange<float>",                                    //  298
  "BSTRange<uint32_t>",                                 //  299
  "BackLightingEnable",                                 //  300
  "BackLightingTintColor",                              //  301
  "BacklightingScale",                                  //  302
  "BacklightingSharpness",                              //  303
  "BacklightingTransparencyFactor",                     //  304
  "BackscatterStrength",                                //  305
  "BackscatterWrap",                                    //  306
  "BaseDistance",                                       //  307
  "BaseFrequency",                                      //  308
  "BeginVisualEffect",                                  //  309
  "Bias",                                               //  310
  "Binding",                                            //  311
  "BindingType",                                        //  312
  "BlendAmount",                                        //  313
  "BlendContrast",                                      //  314
  "BlendMaskContrast",                                  //  315
  "BlendMaskPosition",                                  //  316
  "BlendMode",                                          //  317
  "BlendNormalsAdditively",                             //  318
  "BlendPosition",                                      //  319
  "BlendSoftness",                                      //  320
  "Blender",                                            //  321
  "BlendingMode",                                       //  322
  "BlockClothWindIfInterior",                           //  323
  "Bloom",                                              //  324
  "BloomRangeScale",                                    //  325
  "BloomScale",                                         //  326
  "BloomThresholdOffset",                               //  327
  "BlueChannel",                                        //  328
  "Blur",                                               //  329
  "BlurRadiusValue",                                    //  330
  "BlurStrength",                                       //  331
  "BottomBlendDistanceKm",                              //  332
  "BottomBlendStartKm",                                 //  333
  "BranchFlexibility",                                  //  334
  "Brightness",                                         //  335
  "BuildVersion",                                       //  336
  "CameraDistanceFade",                                 //  337
  "CameraExposure",                                     //  338
  "CameraExposureMode",                                 //  339
  "Category",                                           //  340
  "CelestialBodies",                                    //  341
  "CelestialBodyIlluminanceScale",                      //  342
  "CelestialBodyIlluminanceScaleOverride",              //  343
  "CelestialBodyIndirectIlluminanceScaleOverride",      //  344
  "CenterXValue",                                       //  345
  "CenterYValue",                                       //  346
  "Channel",                                            //  347
  "Children",                                           //  348
  "Cinematic",                                          //  349
  "Circular",                                           //  350
  "Class",                                              //  351
  "ClassReference",                                     //  352
  "ClearDissolveOnEnd",                                 //  353
  "CloudDirectLightingContribution",                    //  354
  "CloudIndirectLightingContribution",                  //  355
  "Collapsed",                                          //  356
  "Collisions",                                         //  357
  "Color",                                              //  358
  "ColorAtTime",                                        //  359
  "ColorGradingAmount",                                 //  360
  "ColorGradingTexture",                                //  361
  "ColorTexture",                                       //  362
  "Colors",                                             //  363
  "Columns",                                            //  364
  "ComponentIndex",                                     //  365
  "ComponentType",                                      //  366
  "ComponentTypes",                                     //  367
  "Components",                                         //  368
  "Config",                                             //  369
  "ConfigurableLODData<3, 3>",                          //  370
  "ConfigurableLODData<4, 4>",                          //  371
  "ContactShadowSoftening",                             //  372
  "Contrast",                                           //  373
  "Controller",                                         //  374
  "Controllers",                                        //  375
  "Controls",                                           //  376
  "CorneaEyeRoughness",                                 //  377
  "CorneaSpecularity",                                  //  378
  "Coverage",                                           //  379
  "Culled",                                             //  380
  "Curve",                                              //  381
  "CurveType",                                          //  382
  "DBID",                                               //  383
  "DEPRECATEDTerrainBlendGradientFactor",               //  384
  "DEPRECATEDTerrainBlendStrength",                     //  385
  "DecalSize",                                          //  386
  "DefaultValue",                                       //  387
  "DefineOverridesMap",                                 //  388
  "Defines",                                            //  389
  "DelayUntilAllTextureDependenciesReady",              //  390
  "Density",                                            //  391
  "DensityDistanceExponent",                            //  392
  "DensityFullDistance",                                //  393
  "DensityNoiseBias",                                   //  394
  "DensityNoiseScale",                                  //  395
  "DensityStartDistance",                               //  396
  "DepolarizationFactor",                               //  397
  "DepthBiasInUlp",                                     //  398
  "DepthMVFixup",                                       //  399
  "DepthMVFixupEdgesOnly",                              //  400
  "DepthOfField",                                       //  401
  "DepthOffsetMaskVertexColorChannel",                  //  402
  "DepthScale",                                         //  403
  "DesiredLODLevelCount",                               //  404
  "DetailBlendMask",                                    //  405
  "DetailBlendMaskUVStream",                            //  406
  "DetailBlenderSettings",                              //  407
  "DiffuseTransmissionScale",                           //  408
  "DigitMask",                                          //  409
  "Dir",                                                //  410
  "DirectTransmissionScale",                            //  411
  "Direction",                                          //  412
  "DirectionalColor",                                   //  413
  "DirectionalIlluminance",                             //  414
  "DirectionalLightIlluminanceOverride",                //  415
  "DirectionalityIntensity",                            //  416
  "DirectionalitySaturation",                           //  417
  "DirectionalityScale",                                //  418
  "DisableSimulatedVisibility",                         //  419
  "DisplacementMidpoint",                               //  420
  "DisplayName",                                        //  421
  "DisplayTypeName",                                    //  422
  "Dissolve",                                           //  423
  "DistanceKm",                                         //  424
  "DistantLODs",                                        //  425
  "DistantLighting",                                    //  426
  "DitherDistanceMax",                                  //  427
  "DitherDistanceMin",                                  //  428
  "DitherScale",                                        //  429
  "DoubleVisionStrengthValue",                          //  430
  "DownStartValue",                                     //  431
  "Duration",                                           //  432
  "DuskDawnPreset",                                     //  433
  "Easing",                                             //  434
  "Edge",                                               //  435
  "EdgeEffectCoefficient",                              //  436
  "EdgeEffectExponent",                                 //  437
  "EdgeFalloffEnd",                                     //  438
  "EdgeFalloffStart",                                   //  439
  "EdgeMaskContrast",                                   //  440
  "EdgeMaskDistanceMax",                                //  441
  "EdgeMaskDistanceMin",                                //  442
  "EdgeMaskMin",                                        //  443
  "Edges",                                              //  444
  "EffectLighting",                                     //  445
  "EffectSequenceMap",                                  //  446
  "EffectSequenceMapMetadata",                          //  447
  "EffectSequenceMetadataID",                           //  448
  "EffectSequenceObjectMetadata",                       //  449
  "ElevationKm",                                        //  450
  "EmissiveClipThreshold",                              //  451
  "EmissiveMaskSourceBlender",                          //  452
  "EmissiveOnlyAutomaticallyApplied",                   //  453
  "EmissiveOnlyEffect",                                 //  454
  "EmissivePaletteTex",                                 //  455
  "EmissiveSourceLayer",                                //  456
  "EmissiveTint",                                       //  457
  "Emittance",                                          //  458
  "EnableAdaptiveLimits",                               //  459
  "EnableCompensationCurve",                            //  460
  "Enabled",                                            //  461
  "End",                                                //  462
  "EndVisualEffect",                                    //  463
  "Entries",                                            //  464
  "EventName",                                          //  465
  "Events",                                             //  466
  "Exposure",                                           //  467
  "ExposureCompensationCurve",                          //  468
  "ExposureMax",                                        //  469
  "ExposureMin",                                        //  470
  "ExposureOffset",                                     //  471
  "Ext",                                                //  472
  "Exterior",                                           //  473
  "ExteriorAndInterior",                                //  474
  "ExternalColorBindingName",                           //  475
  "ExternalLuminanceBindingName",                       //  476
  "FPS",                                                //  477
  "FadeColorValue",                                     //  478
  "FadeDistanceKm",                                     //  479
  "FadeStartKm",                                        //  480
  "FallbackToRoot",                                     //  481
  "FalloffStartAngle",                                  //  482
  "FalloffStartAngles",                                 //  483
  "FalloffStartOpacities",                              //  484
  "FalloffStartOpacity",                                //  485
  "FalloffStopAngle",                                   //  486
  "FalloffStopAngles",                                  //  487
  "FalloffStopOpacities",                               //  488
  "FalloffStopOpacity",                                 //  489
  "FarFadeValue",                                       //  490
  "FarOpacityValue",                                    //  491
  "FarPlaneValue",                                      //  492
  "FarStartValue",                                      //  493
  "File",                                               //  494
  "FileName",                                           //  495
  "First",                                              //  496
  "FirstBlenderIndex",                                  //  497
  "FirstBlenderMode",                                   //  498
  "FirstLayerIndex",                                    //  499
  "FirstLayerMaskIndex",                                //  500
  "FirstLayerTint",                                     //  501
  "FixedValue",                                         //  502
  "FlipBackFaceNormalsInViewSpace",                     //  503
  "FlowExtent",                                         //  504
  "FlowIsAnimated",                                     //  505
  "FlowMap",                                            //  506
  "FlowMapAndTexturesAreFlipbooks",                     //  507
  "FlowSourceUVChannel",                                //  508
  "FlowSpeed",                                          //  509
  "FlowUVOffset",                                       //  510
  "FlowUVScale",                                        //  511
  "FoamTextureDistortion",                              //  512
  "FoamTextureScrollSpeed",                             //  513
  "Fog",                                                //  514
  "FogDensity",                                         //  515
  "FogFar",                                             //  516
  "FogFarHigh",                                         //  517
  "FogMap",                                             //  518
  "FogMapContribution",                                 //  519
  "FogNear",                                            //  520
  "FogNearHigh",                                        //  521
  "FogScaleValue",                                      //  522
  "FogThickness",                                       //  523
  "Foliage",                                            //  524
  "ForceRenderBeforeOIT",                               //  525
  "ForceStopOnDetach",                                  //  526
  "ForceStopSound",                                     //  527
  "FormFolderPath",                                     //  528
  "FrequencyMultiplier",                                //  529
  "Frosting",                                           //  530
  "FrostingBlurBias",                                   //  531
  "FrostingUnblurredBackgroundAlphaBlend",              //  532
  "GeoShareBehavior",                                   //  533
  "GlareColor",                                         //  534
  "GlobalLayerNoiseData",                               //  535
  "GreenChannel",                                       //  536
  "HDAComponentIdx",                                    //  537
  "HDAFilePath",                                        //  538
  "HDAVersion",                                         //  539
  "HableShoulderAngle",                                 //  540
  "HableShoulderLength",                                //  541
  "HableShoulderStrength",                              //  542
  "HableToeLength",                                     //  543
  "HableToeStrength",                                   //  544
  "HasData",                                            //  545
  "HasErrors",                                          //  546
  "HasOpacity",                                         //  547
  "HashMap",                                            //  548
  "Height",                                             //  549
  "HeightAboveTerrain",                                 //  550
  "HeightBlendFactor",                                  //  551
  "HeightBlendThreshold",                               //  552
  "HeightFalloffExponent",                              //  553
  "HeightKm",                                           //  554
  "HelpText",                                           //  555
  "HighFrequencyNoiseDensityScale",                     //  556
  "HighFrequencyNoiseScale",                            //  557
  "HighGUID",                                           //  558
  "HorizonFog",                                         //  559
  "HorizonScatteringBlendScale",                        //  560
  "HorizontalAngle",                                    //  561
  "HoudiniDataComponent",                               //  562
  "HurstExponent",                                      //  563
  "ID",                                                 //  564
  "ISO",                                                //  565
  "Id",                                                 //  566
  "IgnoreSmallHeadparts",                               //  567
  "IgnoreWeapons",                                      //  568
  "IgnoredBrightsPercentile",                           //  569
  "IgnoredDarksPercentile",                             //  570
  "ImageSpaceSettings",                                 //  571
  "ImageSpaceSettings::AmbientOcclusionSettings",       //  572
  "ImageSpaceSettings::BloomSettings",                  //  573
  "ImageSpaceSettings::BlurSettings",                   //  574
  "ImageSpaceSettings::CinematicSettings",              //  575
  "ImageSpaceSettings::DepthOfFieldSettings",           //  576
  "ImageSpaceSettings::ExposureSettings",               //  577
  "ImageSpaceSettings::ExposureSettings::AutoExposureSettings",         //  578
  "ImageSpaceSettings::ExposureSettings::CameraExposureSettings",       //  579
  "ImageSpaceSettings::ExposureSettings::LuminanceHistogramSettings",   //  580
  "ImageSpaceSettings::FogSettings",                    //  581
  "ImageSpaceSettings::IndirectLightingSettings",       //  582
  "ImageSpaceSettings::RadialBlurSettings",             //  583
  "ImageSpaceSettings::SunAndSkySettings",              //  584
  "ImageSpaceSettings::ToneMappingSettings",            //  585
  "ImageSpaceSettings::VolumetricLightingSettings",     //  586
  "Index",                                              //  587
  "IndirectDiffuseMultiplier",                          //  588
  "IndirectLighting",                                   //  589
  "IndirectLightingSkyScaleOverride",                   //  590
  "IndirectLightingSkyTargetEv100",                     //  591
  "IndirectLightingSkyTargetStrength",                  //  592
  "IndirectSpecRoughness",                              //  593
  "IndirectSpecularMultiplier",                         //  594
  "IndirectSpecularScale",                              //  595
  "IndirectSpecularTransmissionScale",                  //  596
  "InitialAngularVelocity",                             //  597
  "InitialAngularVelocityNoise",                        //  598
  "InitialLinearVelocity",                              //  599
  "InitialLinearVelocityNoise",                         //  600
  "InitialOffset",                                      //  601
  "InnerFadeDistance",                                  //  602
  "InorganicResources",                                 //  603
  "Input",                                              //  604
  "InputDistance",                                      //  605
  "Instances",                                          //  606
  "IntensityValue",                                     //  607
  "InterpretAs",                                        //  608
  "Interval",                                           //  609
  "IrisDepthPosition",                                  //  610
  "IrisDepthTransitionRatio",                           //  611
  "IrisSpecularity",                                    //  612
  "IrisTotalDepth",                                     //  613
  "IrisUVSize",                                         //  614
  "IsAFlipbook",                                        //  615
  "IsAlphaTested",                                      //  616
  "IsDecal",                                            //  617
  "IsDetailBlendMaskSupported",                         //  618
  "IsEmpty",                                            //  619
  "IsGlass",                                            //  620
  "IsMembrane",                                         //  621
  "IsPermanent",                                        //  622
  "IsPlanet",                                           //  623
  "IsProjected",                                        //  624
  "IsSampleInterpolating",                              //  625
  "IsSpikyHair",                                        //  626
  "IsTeeth",                                            //  627
  "Key",                                                //  628
  "KeyMaterialPathForm",                                //  629
  "Keywords",                                           //  630
  "KillSound",                                          //  631
  "LODMeshOverrides",                                   //  632
  "Label",                                              //  633
  "Layer",                                              //  634
  "LayerIndex",                                         //  635
  "Layers",                                             //  636
  "LeafAmplitude",                                      //  637
  "LeafFrequency",                                      //  638
  "LeafSecondaryMotionAmount",                          //  639
  "LeafSecondaryMotionCutOff",                          //  640
  "LensFlareAttachmentComponent",                       //  641
  "LensFlareAttachmentDefine",                          //  642
  "LensFlareCloudOcclusionStrength",                    //  643
  "LensFlareDefines",                                   //  644
  "LightAttachmentConfiguration",                       //  645
  "LightAttachmentDefine",                              //  646
  "LightAttachmentFormComponent",                       //  647
  "LightAttachmentRef",                                 //  648
  "LightLuminanceMultiplier",                           //  649
  "LightingPower",                                      //  650
  "LightingWrap",                                       //  651
  "LightningColor",                                     //  652
  "LightningDistanceMax",                               //  653
  "LightningDistanceMin",                               //  654
  "LightningFieldOfView",                               //  655
  "LightningStrikeEffect",                              //  656
  "Loop",                                               //  657
  "LoopSegment",                                        //  658
  "Loops",                                              //  659
  "LowGUID",                                            //  660
  "LowLOD",                                             //  661
  "LowLODRootMaterial",                                 //  662
  "LuminanceAtTime",                                    //  663
  "LuminanceHistogram",                                 //  664
  "LuminousEmittance",                                  //  665
  "Map",                                                //  666
  "MapMetadata",                                        //  667
  "MappingsA",                                          //  668
  "Mask",                                               //  669
  "MaskDistanceFromShoreEnd",                           //  670
  "MaskDistanceFromShoreStart",                         //  671
  "MaskDistanceRampWidth",                              //  672
  "MaskIntensityMax",                                   //  673
  "MaskIntensityMin",                                   //  674
  "MaskNoiseAmp",                                       //  675
  "MaskNoiseAnimSpeed",                                 //  676
  "MaskNoiseBias",                                      //  677
  "MaskNoiseFreq",                                      //  678
  "MaskNoiseGlobalScale",                               //  679
  "MaskWaveParallax",                                   //  680
  "Material",                                           //  681
  "MaterialMaskIntensityScale",                         //  682
  "MaterialOverallAlpha",                               //  683
  "MaterialPath",                                       //  684
  "MaterialProperty",                                   //  685
  "MaterialTypeOverride",                               //  686
  "Materials",                                          //  687
  "Max",                                                //  688
  "MaxConcentrationPlankton",                           //  689
  "MaxConcentrationSediment",                           //  690
  "MaxConcentrationYellowMatter",                       //  691
  "MaxDelay",                                           //  692
  "MaxDepthOffset",                                     //  693
  "MaxDisplacement",                                    //  694
  "MaxFogDensity",                                      //  695
  "MaxFogThickness",                                    //  696
  "MaxIndex",                                           //  697
  "MaxInput",                                           //  698
  "MaxMeanFreePath",                                    //  699
  "MaxOffsetEmittance",                                 //  700
  "MaxParralaxOcclusionSteps",                          //  701
  "MaxValue",                                           //  702
  "MeanFreePath",                                       //  703
  "MediumLODRootMaterial",                              //  704
  "MeshFileOverride",                                   //  705
  "MeshLODDistanceOverride",                            //  706
  "MeshLODs",                                           //  707
  "MeshOverrides",                                      //  708
  "Metadata",                                           //  709
  "Mie",                                                //  710
  "MieCoef",                                            //  711
  "Min",                                                //  712
  "MinDelay",                                           //  713
  "MinFogDensity",                                      //  714
  "MinFogThickness",                                    //  715
  "MinIndex",                                           //  716
  "MinInput",                                           //  717
  "MinMeanFreePath",                                    //  718
  "MinOffsetEmittance",                                 //  719
  "MinValue",                                           //  720
  "MipBase",                                            //  721
  "Misc",                                               //  722
  "Mode",                                               //  723
  "MoleculesPerUnitVolume",                             //  724
  "MoonGlare",                                          //  725
  "Moonlight",                                          //  726
  "MostSignificantLayer",                               //  727
  "MotionBlurStrengthValue",                            //  728
  "Name",                                               //  729
  "NavMeshAreaFlag",                                    //  730
  "NavMeshSplineExtraData::ChunkData",                  //  731
  "NavMeshSplineExtraData::ChunkDataRef",               //  732
  "NearFadeValue",                                      //  733
  "NearOpacityValue",                                   //  734
  "NearPlaneValue",                                     //  735
  "NearStartValue",                                     //  736
  "NestedTracks",                                       //  737
  "NiPoint3",                                           //  738
  "NightPreset",                                        //  739
  "NoHalfResOptimization",                              //  740
  "NoLAngularDamping",                                  //  741
  "NoLinearDamping",                                    //  742
  "NoSky",                                              //  743
  "Node",                                               //  744
  "NodeAttachmentConfiguration",                        //  745
  "NodeName",                                           //  746
  "Nodes",                                              //  747
  "NoiseBias",                                          //  748
  "NoiseContribution",                                  //  749
  "NoiseMaskTexture",                                   //  750
  "NoiseScale",                                         //  751
  "NoiseScrollingVelocity",                             //  752
  "NormalAffectsStrength",                              //  753
  "NormalOverride",                                     //  754
  "NormalShadowStrength",                               //  755
  "NormalTexture",                                      //  756
  "NumLODMaterials",                                    //  757
  "Object",                                             //  758
  "ObjectAttachmentConfiguration",                      //  759
  "ObjectID",                                           //  760
  "Objects",                                            //  761
  "Offset",                                             //  762
  "Op",                                                 //  763
  "OpacitySourceLayer",                                 //  764
  "OpacityTexture",                                     //  765
  "OpacityUVStream",                                    //  766
  "Optimized",                                          //  767
  "Order",                                              //  768
  "OuterFadeDistance",                                  //  769
  "OverallBlendAmount",                                 //  770
  "OverrideAttachType",                                 //  771
  "OverrideInitialVelocities",                          //  772
  "OverrideLevelCount",                                 //  773
  "OverrideMaterial",                                   //  774
  "OverrideMaterialPath",                               //  775
  "OverrideMeshLODDistance",                            //  776
  "OverrideSearchMethod",                               //  777
  "OverrideToneMapping",                                //  778
  "Overrides",                                          //  779
  "OzoneAbsorptionCoef",                                //  780
  "ParallaxOcclusionScale",                             //  781
  "ParallaxOcclusionShadows",                           //  782
  "ParamIndex",                                         //  783
  "ParameterName",                                      //  784
  "ParametersA",                                        //  785
  "Parent",                                             //  786
  "ParticleAttachmentConfiguration",                    //  787
  "ParticleFormComponent",                              //  788
  "ParticleRenderState",                                //  789
  "ParticleSystemDefine",                               //  790
  "ParticleSystemDefineOverrides",                      //  791
  "ParticleSystemDefineRef",                            //  792
  "ParticleSystemPath",                                 //  793
  "ParticleSystemReferenceDefine",                      //  794
  "Path",                                               //  795
  "PathStr",                                            //  796
  "PersistentID",                                       //  797
  "PhytoplanktonReflectanceColorB",                     //  798
  "PhytoplanktonReflectanceColorG",                     //  799
  "PhytoplanktonReflectanceColorR",                     //  800
  "PlacedWater",                                        //  801
  "Planes",                                             //  802
  "PlanetStarGlowBackgroundScale",                      //  803
  "PlanetStarfieldBackgroundGIContribution",            //  804
  "PlanetStarfieldBackgroundScale",                     //  805
  "PlanetStarfieldStarBrightnessScale",                 //  806
  "PlayMode",                                           //  807
  "PlayOnCulledNodes",                                  //  808
  "PlayerHUDEffect",                                    //  809
  "Position",                                           //  810
  "PositionOffset",                                     //  811
  "PositionOffsetEnabled",                              //  812
  "PrecipFadeIn",                                       //  813
  "PrecipFadeOut",                                      //  814
  "Precipitation",                                      //  815
  "PreferREFR",                                         //  816
  "PreferREFREnabled",                                  //  817
  "PresetData",                                         //  818
  "PreviewModelPath",                                   //  819
  "PrewarmTime",                                        //  820
  "ProjectedDecalSetting",                              //  821
  "Properties",                                         //  822
  "Property",                                           //  823
  "RadialBlur",                                         //  824
  "RampDownValue",                                      //  825
  "RampUpValue",                                        //  826
  "RandomPlaySpeedRange",                               //  827
  "RandomTimeOffset",                                   //  828
  "Range",                                              //  829
  "RaycastDirection",                                   //  830
  "RaycastLength",                                      //  831
  "Rayleigh",                                           //  832
  "RayleighCoef",                                       //  833
  "ReceiveDirectionalShadows",                          //  834
  "ReceiveNonDirectionalShadows",                       //  835
  "ReciprocalTickRate",                                 //  836
  "RedChannel",                                         //  837
  "RefID",                                              //  838
  "ReferenceDefines",                                   //  839
  "References",                                         //  840
  "ReflectanceB",                                       //  841
  "ReflectanceG",                                       //  842
  "ReflectanceR",                                       //  843
  "ReflectionProbeCellComponent",                       //  844
  "ReflectionProbeInstanceData",                        //  845
  "RefractiveIndexOfAir",                               //  846
  "RemapAlbedo",                                        //  847
  "RemapEmissive",                                      //  848
  "RemapOpacity",                                       //  849
  "RenderLayer",                                        //  850
  "Replacement",                                        //  851
  "RequiresNodeType",                                   //  852
  "ResetOnEnd",                                         //  853
  "ResetOnLoop",                                        //  854
  "ResolutionHint",                                     //  855
  "RespectSceneTransform",                              //  856
  "RevertMaterialOnSequenceEnd",                        //  857
  "RotationAngle",                                      //  858
  "RotationOffset",                                     //  859
  "RotationOffsetEnabled",                              //  860
  "Roughness",                                          //  861
  "RoundToNearest",                                     //  862
  "Route",                                              //  863
  "Rows",                                               //  864
  "SSSStrength",                                        //  865
  "SSSWidth",                                           //  866
  "Saturation",                                         //  867
  "ScaleOffset",                                        //  868
  "ScaleOffsetEnabled",                                 //  869
  "Scattering",                                         //  870
  "ScatteringFar",                                      //  871
  "ScatteringScale",                                    //  872
  "ScatteringTransition",                               //  873
  "ScatteringVolumeFar",                                //  874
  "ScatteringVolumeNear",                               //  875
  "ScleraEyeRoughness",                                 //  876
  "ScleraSpecularity",                                  //  877
  "SearchFromTopLevelFadeNode",                         //  878
  "SearchMethod",                                       //  879
  "Second",                                             //  880
  "SecondBlenderIndex",                                 //  881
  "SecondBlenderMode",                                  //  882
  "SecondLayerActive",                                  //  883
  "SecondLayerIndex",                                   //  884
  "SecondLayerMaskIndex",                               //  885
  "SecondLayerTint",                                    //  886
  "SecondMostSignificantLayer",                         //  887
  "SedimentReflectanceColorB",                          //  888
  "SedimentReflectanceColorG",                          //  889
  "SedimentReflectanceColorR",                          //  890
  "SequenceID",                                         //  891
  "SequenceName",                                       //  892
  "Sequences",                                          //  893
  "Settings",                                           //  894
  "SettingsTemplate",                                   //  895
  "Shadows",                                            //  896
  "ShakeMultiplier",                                    //  897
  "ShakeType",                                          //  898
  "ShouldRescale",                                      //  899
  "SkyLightingMultiplier",                              //  900
  "SoftEffect",                                         //  901
  "SoftFalloffDepth",                                   //  902
  "Sound",                                              //  903
  "SoundEffects",                                       //  904
  "SoundHook",                                          //  905
  "Sounds",                                             //  906
  "SourceDirection",                                    //  907
  "SourceDirectoryHash",                                //  908
  "SourceID",                                           //  909
  "SpaceGlowBackgroundScaleOverride",                   //  910
  "SpawnMethod",                                        //  911
  "SpecLobe0RoughnessScale",                            //  912
  "SpecLobe1RoughnessScale",                            //  913
  "SpecScale",                                          //  914
  "SpecularOpacityOverride",                            //  915
  "SpecularTransmissionScale",                          //  916
  "Speed",                                              //  917
  "SpellData",                                          //  918
  "SpellItems",                                         //  919
  "SplineColor_Packed",                                 //  920
  "SplineSide",                                         //  921
  "StarfieldBackgroundScaleOverride",                   //  922
  "StarfieldStarBrightnessScaleOverride",               //  923
  "Stars",                                              //  924
  "Start",                                              //  925
  "StartEvent",                                         //  926
  "StartTargetIndex",                                   //  927
  "StartValue",                                         //  928
  "StaticVisibility",                                   //  929
  "StopEvent",                                          //  930
  "StreamID",                                           //  931
  "Strength",                                           //  932
  "StrengthValue",                                      //  933
  "SubWeathers",                                        //  934
  "Sun",                                                //  935
  "SunAndSky",                                          //  936
  "SunColor",                                           //  937
  "SunGlare",                                           //  938
  "SunGlareColor",                                      //  939
  "SunIlluminance",                                     //  940
  "Sunlight",                                           //  941
  "SurfaceHeightMap",                                   //  942
  "SwapsCollection",                                    //  943
  "TESImageSpace",                                      //  944
  "TESImageSpaceModifier",                              //  945
  "Tangent",                                            //  946
  "TangentBend",                                        //  947
  "TargetID",                                           //  948
  "TargetUVStream",                                     //  949
  "TerrainBlendGradientFactor",                         //  950
  "TerrainBlendStrength",                               //  951
  "TerrainMatch",                                       //  952
  "TexcoordScaleAndBias",                               //  953
  "TexcoordScale_XY",                                   //  954
  "TexcoordScale_XZ",                                   //  955
  "TexcoordScale_YZ",                                   //  956
  "Texture",                                            //  957
  "TextureMappingType",                                 //  958
  "TextureShadowOffset",                                //  959
  "TextureShadowStrength",                              //  960
  "Thickness",                                          //  961
  "ThicknessNoiseBias",                                 //  962
  "ThicknessNoiseScale",                                //  963
  "ThicknessTexture",                                   //  964
  "Thin",                                               //  965
  "ThirdLayerActive",                                   //  966
  "ThirdLayerIndex",                                    //  967
  "ThirdLayerMaskIndex",                                //  968
  "ThirdLayerTint",                                     //  969
  "Threshold",                                          //  970
  "ThunderFadeIn",                                      //  971
  "ThunderFadeOut",                                     //  972
  "TicksPerSecond",                                     //  973
  "Tiling",                                             //  974
  "TilingDistance",                                     //  975
  "TilingPerKm",                                        //  976
  "Time",                                               //  977
  "TimeMultiplier",                                     //  978
  "TimelineStartTime",                                  //  979
  "TimelineUnitsPerPixel",                              //  980
  "Tint",                                               //  981
  "TintColorValue",                                     //  982
  "ToneMapE",                                           //  983
  "ToneMapping",                                        //  984
  "TopBlendDistanceKm",                                 //  985
  "TopBlendStartKm",                                    //  986
  "Tracks",                                             //  987
  "TransDelta",                                         //  988
  "TransformHandling",                                  //  989
  "TransformMode",                                      //  990
  "TransitionEndAngle",                                 //  991
  "TransitionStartAngle",                               //  992
  "TransitionThreshold",                                //  993
  "TransmissiveScale",                                  //  994
  "TransmittanceSourceLayer",                           //  995
  "TransmittanceWidth",                                 //  996
  "TrunkFlexibility",                                   //  997
  "TurbulenceDirectionAmplitude",                       //  998
  "TurbulenceDirectionFrequency",                       //  999
  "TurbulenceSpeedAmplitude",                           // 1000
  "TurbulenceSpeedFrequency",                           // 1001
  "Type",                                               // 1002
  "UVStreamTargetBlender",                              // 1003
  "UVStreamTargetLayer",                                // 1004
  "UniqueID",                                           // 1005
  "UseAsInteriorCriteria",                              // 1006
  "UseBoundsToScaleDissolve",                           // 1007
  "UseCustomCoefficients",                              // 1008
  "UseDetailBlendMask",                                 // 1009
  "UseDigitMask",                                       // 1010
  "UseDitheredTransparency",                            // 1011
  "UseFallOff",                                         // 1012
  "UseGBufferNormals",                                  // 1013
  "UseNodeLocalRotation",                               // 1014
  "UseNoiseMaskTexture",                                // 1015
  "UseOutdoorExposure",                                 // 1016
  "UseOutdoorLUT",                                      // 1017
  "UseOzoneAbsorptionApproximation",                    // 1018
  "UseParallaxOcclusionMapping",                        // 1019
  "UseRGBFallOff",                                      // 1020
  "UseRandomOffset",                                    // 1021
  "UseSSS",                                             // 1022
  "UseStartTargetIndex",                                // 1023
  "UseTargetForDepthOfField",                           // 1024
  "UseTargetForRadialBlur",                             // 1025
  "UseVertexAlpha",                                     // 1026
  "UseVertexColor",                                     // 1027
  "UseWorldAlignedRaycastDirection",                    // 1028
  "UserDuration",                                       // 1029
  "UsesDirectionality",                                 // 1030
  "Value",                                              // 1031
  "Variables",                                          // 1032
  "VariationStrength",                                  // 1033
  "Version",                                            // 1034
  "VertexColorBlend",                                   // 1035
  "VertexColorChannel",                                 // 1036
  "VerticalAngle",                                      // 1037
  "VerticalTiling",                                     // 1038
  "VeryLowLODRootMaterial",                             // 1039
  "VisibilityMultiplier",                               // 1040
  "VolatilityMultiplier",                               // 1041
  "VolumetricIndirectLightContribution",                // 1042
  "VolumetricLighting",                                 // 1043
  "VolumetricLightingDirectionalAnisoScale",            // 1044
  "VolumetricLightingDirectionalLightScale",            // 1045
  "WarmUp",                                             // 1046
  "WaterDepthBlur",                                     // 1047
  "WaterEdgeFalloff",                                   // 1048
  "WaterEdgeNormalFalloff",                             // 1049
  "WaterRefractionMagnitude",                           // 1050
  "WaterWetnessMaxDepth",                               // 1051
  "WaveAmplitude",                                      // 1052
  "WaveDistortionAmount",                               // 1053
  "WaveFlipWaveDirection",                              // 1054
  "WaveParallaxFalloffBias",                            // 1055
  "WaveParallaxFalloffScale",                           // 1056
  "WaveParallaxInnerStrength",                          // 1057
  "WaveParallaxOuterStrength",                          // 1058
  "WaveScale",                                          // 1059
  "WaveShoreFadeInnerDistance",                         // 1060
  "WaveShoreFadeOuterDistance",                         // 1061
  "WaveSpawnFadeInDistance",                            // 1062
  "WaveSpeed",                                          // 1063
  "WeatherActivateEffect",                              // 1064
  "WeatherChoice",                                      // 1065
  "Weight",                                             // 1066
  "WeightMultiplier",                                   // 1067
  "WhitePointValue",                                    // 1068
  "WindDirectionOverrideEnabled",                       // 1069
  "WindDirectionOverrideValue",                         // 1070
  "WindDirectionRange",                                 // 1071
  "WindScale",                                          // 1072
  "WindStrengthVariationMax",                           // 1073
  "WindStrengthVariationMin",                           // 1074
  "WindStrengthVariationSpeed",                         // 1075
  "WindTurbulence",                                     // 1076
  "WorldspaceScaleFactor",                              // 1077
  "WriteMask",                                          // 1078
  "XCurve",                                             // 1079
  "XMCOLOR",                                            // 1080
  "XMFLOAT2",                                           // 1081
  "XMFLOAT3",                                           // 1082
  "XMFLOAT4",                                           // 1083
  "YCurve",                                             // 1084
  "YellowMatterReflectanceColorB",                      // 1085
  "YellowMatterReflectanceColorG",                      // 1086
  "YellowMatterReflectanceColorR",                      // 1087
  "ZCurve",                                             // 1088
  "ZTest",                                              // 1089
  "ZWrite",                                             // 1090
  "a",                                                  // 1091
  "b",                                                  // 1092
  "g",                                                  // 1093
  "pArtForm",                                           // 1094
  "pClimateOverride",                                   // 1095
  "pCloudCardSequence",                                 // 1096
  "pClouds",                                            // 1097
  "pConditionForm",                                     // 1098
  "pConditions",                                        // 1099
  "pDefineCollection",                                  // 1100
  "pDisplayNameKeyword",                                // 1101
  "pEventForm",                                         // 1102
  "pExplosionForm",                                     // 1103
  "pExternalForm",                                      // 1104
  "pFalloff",                                           // 1105
  "pFormReference",                                     // 1106
  "pImageSpace",                                        // 1107
  "pImageSpaceDay",                                     // 1108
  "pImageSpaceForm",                                    // 1109
  "pImageSpaceNight",                                   // 1110
  "pImpactDataSet",                                     // 1111
  "pLensFlare",                                         // 1112
  "pLightForm",                                         // 1113
  "pLightningFX",                                       // 1114
  "pMainSpell",                                         // 1115
  "pOptionalPhotoModeEffect",                           // 1116
  "pParent",                                            // 1117
  "pParentForm",                                        // 1118
  "pPrecipitationEffect",                               // 1119
  "pPreviewForm",                                       // 1120
  "pProjectedDecalForm",                                // 1121
  "pSource",                                            // 1122
  "pSpell",                                             // 1123
  "pSunPresetOverride",                                 // 1124
  "pTimeOfDayData",                                     // 1125
  "pTransitionSpell",                                   // 1126
  "pVisualEffect",                                      // 1127
  "pVolumeticLighting",                                 // 1128
  "pWindForce",                                         // 1129
  "r",                                                  // 1130
  "spController",                                       // 1131
  "upControllers",                                      // 1132
  "upDir",                                              // 1133
  "upMap",                                              // 1134
  "upObjectToAttach",                                   // 1135
  "upObjectToSpawn",                                    // 1136
  "w",                                                  // 1137
  "x",                                                  // 1138
  "y",                                                  // 1139
  "z"                                                   // 1140
};

